apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-01
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: test
          - stage: uat
          - stage: prod
  template:
    metadata:
      name: kargo-demo-01-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-01:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/cyberslot/kargo-examples.git
        # Kargo will update targetRevision to move new commits from main into each stage
        targetRevision: placeholder
        path: stages/{{stage}}
        kustomize:
          images:
            - public.ecr.aws/nginx/nginx=public.ecr.aws/nginx/nginx:1.28-alpine-slim
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-01-{{stage}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.targetRevision
