apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-10
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: test
          - stage: uat
          - stage: prod
  template:
    metadata:
      name: kargo-demo-10-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-10:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/cyberslot/kargo-examples.git
        # Kargo will update this branch to move new images into this stage
        targetRevision: 10/stage/{{stage}}
        path: ./kargo-demo/templates
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-10-{{stage}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
